const UPSTREAM_COMMIT = "7e0e77f88fc113a76fe363504125f5b36b8a3fe3";

export function nightscoutStatus(now = new Date()): Record<string, unknown> {
  return {
    status: "ok",
    name: "Nightscout",
    version: "15.0.7-nscf.1",
    versionNum: 150007,
    head: UPSTREAM_COMMIT,
    serverTime: now.toISOString(),
    serverTimeEpoch: now.getTime(),
    apiEnabled: true,
    careportalEnabled: false,
    boluscalcEnabled: false,
    runtimeState: "loaded",
    settings: {
      units: "mg/dl",
      timeFormat: 24,
      dayStart: 7,
      dayEnd: 21,
      nightMode: false,
      editMode: false,
      showRawbg: "never",
      customTitle: "Nightscout",
      theme: "default",
      language: "en",
      scaleY: "log",
      showPlugins: "delta direction timeago",
      showForecast: "ar2",
      focusHours: 3,
      heartbeat: 60,
      authDefaultRoles: "readable",
      authenticationPromptOnLoad: false,
      adminNotifiesEnabled: false,
      alarmTypes: [],
      alarmUrgentHigh: false,
      alarmHigh: false,
      alarmLow: false,
      alarmUrgentLow: false,
      alarmTimeagoWarn: false,
      alarmTimeagoWarnMins: 15,
      alarmTimeagoUrgent: false,
      alarmTimeagoUrgentMins: 30,
      alarmPumpBatteryLow: false,
      thresholds: {
        bgHigh: 260,
        bgTargetTop: 180,
        bgTargetBottom: 80,
        bgLow: 55,
      },
      enable: ["bgnow", "delta", "direction", "timeago", "ar2"],
    },
    extendedSettings: {},
    nscf: {
      phase: 1,
      transport: "rest-polling-socket-shim",
      dataPolicy: "simulated-only",
      upstreamRelease: "v15.0.7",
    },
  };
}
